Cache
Oleksandr-Mokryi/Flash-n-Fresh pull request #11
Opened 2021-06-07 16:51 UTC by Oleksandr-Mokryi

2021-06-07 16:56 UTC, Oleksandr-Mokryi commented
Случайно слил не те ветки. Пересоздал пр.
Ссылка на старый https://github.com/Oleksandr-Mokryi/Flash-n-Fresh/pull/7

2021-06-12 16:58 UTC, serhii-shkodenko requested changes

2021-06-12 16:58 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Units/Product.cs
> +        public DateTime updateMark { get; set; }
1. Свойства следует именовать в `PascalCase`. Вот детальнее по [ссылке](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties). 
2. Публичный сеттер для свойства, хранящего данные о времени повледней модификации - не очень хорошая идея. Или удали его, или используй `init`.

2021-06-12 16:58 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Units/Product.cs
>          public Vendor vendor;
Свойства следует именовать в `PascalCase`. Вот детальнее по [ссылке](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-properties).

2021-06-12 16:58 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +        public IEnumerable<T> GetFromCache<T>(string key) where T : class
В принципе лучше просигнализировать, что из метода может не вернуться объект кеша и добавить в имя `OrEmpty`.

2021-06-12 16:58 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +                return new List<T>();
Чтобы не размещать в памяти новй объект списка, который не собираешься заполнять, пользуйся для таких случаев `Array.Empty<T>()`;

2021-06-12 18:23 UTC, serhii-shkodenko requested changes

2021-06-12 18:23 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +                _cache.CacheData[key] = value;
Нужно проверить, что такого ключа не существует, иначе твой словарь выдаст исключение.

2021-06-12 18:23 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/ProductWorker.cs
> +            if (_cacheManager.GetFromCacheOrEmpty<Product>(typeof(Product).ToString())?.Count() != 0)
Здесь и ниже ты два раз обращаешься к кешу. Можно обойтись одним запросом: получи результат и проверь его, если он не пустой - верни его.

2021-06-12 18:39 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +                _cache.CacheData[key] = value;
У меня нет исключения если я пытаюсь по одному ключу положить разные значения один за другим. Оно просто по текущему существующему ключу меняет значение на новое.

2021-06-12 18:48 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +                _cache.CacheData[key] = value;
Да, конечно, здесь не будет исключения.

2021-08-20 20:18 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-08-30 18:47 UTC, closed without merging