Async task
Oleksandr-Mokryi/Flash-n-Fresh pull request #12
Opened 2021-06-07 19:18 UTC by Oleksandr-Mokryi

impemented async data recieve from privat bank with json and calculaing order price in UAH

2021-06-14 14:40 UTC, serhii-shkodenko commented
Конфликт поправь, пожалуйста.

2021-06-14 14:50 UTC, Oleksandr-Mokryi commented
> Конфликт поправь, пожалуйста.

Готово

2021-08-23 08:08 UTC, serhii-shkodenko requested changes

2021-08-23 09:00 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/ICurrency.cs
> +        string Ccy { get; set; }
В классе модификаторы стоят. В интерфейсе мы public не указываем.

2021-08-23 09:18 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/ICurrency.cs
> +        string Ccy { get; set; }
Да, конечно, ты прав. Я упустил, что ты сделал интерфейс и класс. 

В интерфейсе эти атрибутся избыточны, поскольку они не применяются в реализованном нами классе (тебе все равно пришлось их проставлять в классе). (Если бы ты наследовался от класса, где были бы атрибуты на свойствах, то вот они бы применялись). При этом для этой задачи наличие интерфейса в целом избыточно. Для моделей данных интерфейсы обычно не делают. 

При этом атрибуты все же могут применяться вместе с интерфейсами. Например, при разработке WCF сервисов для описания контрактов.

2021-08-23 09:20 UTC, serhii-shkodenko approved these changes
Выглядит хорошо, можно мержить.

2021-08-23 09:55 UTC, merged