implemented adding to dataBase and creating orders for customer
Oleksandr-Mokryi/Flash-n-Fresh pull request #3
Opened 2021-04-21 19:31 UTC by Oleksandr-Mokryi

2021-04-27 02:27 UTC, serhii-shkodenko requested changes

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/ConsoleWorkers/ConsoleStrings.cs
> +    public class ConsoleStrings
Такой класс вполне можно сделать статическим со статическими свойствами.

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/ConsoleWorkers/ConsoleWriter.cs
> +        public ConsoleStrings strings = new ConsoleStrings();
Класс не должен содержать публичных полей. Попробуй либо свойство, либо приватное поле.

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
Нарушается принцип Dependency inversion principle. Используй интерфейсы.

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        private Base innerBase;
Не хватает модификатора `readonly`.

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/OrderWorker.cs
> +        private Order order;
Не хватает модификатора `readonly`.

2021-04-27 02:27 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/OrderWorker.cs
> +        public OrderWorker(BaseWorker worker, Order newOrder)
Нарушается принцип Dependency inversion principle. Используй интерфейсы.

2021-04-27 16:44 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/ConsoleWorkers/ConsoleStrings.cs
> +    public class ConsoleStrings
Я специально старался не допускать статических свойств или классов. Но если нужно, то исправлю.

2021-04-27 16:54 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/ConsoleWorkers/ConsoleStrings.cs
> +    public class ConsoleStrings
Я бы оценил это стремление как такое, которое позволит в дальнейшем избежать многих проблем. Здесь однозначный плюс. Идеально было бы использовать `resx` файлы, например, но это скорее тема локализации, мы ее не касались, поэтому здесь можно применить и статический файл.

2021-04-27 17:03 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
В данном случае baseWithData это набор списков со всеми данными. Здесь имеется ввиду использование интерфейсов для классов, которые отвечают за чтение и запись в консоль?

2021-04-27 17:17 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
Глянул на код внимательней. Лучше всего, на мой взгляд, будет сделать отдельные классы для управления каждой сущностью-моделью. В такой класс в качестве зависимости будет приходить хранилище. Методы этих отдельных классов будут управлять данными в хранилище. 

Вывод на консоль из  этого класса или в класса-манипуляторах данными следует полносью исключить, иначе нарушается Single responsibility principle.

2021-04-27 19:14 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/ConsoleWorkers/ConsoleStrings.cs
> +    public class ConsoleStrings
Понял общую суть и основные ошибки, Переделаю с момента создания моделей.

2021-04-27 19:30 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
Понял общую суть и основные ошибки, Переделаю с момента создания моделей.

2021-05-02 19:56 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
Полностью, практически с нуля переписал всё, стараясь учитывать требования.

2021-05-02 19:57 UTC, Oleksandr-Mokryi commented
Полностью, практически с нуля переписал всё, стараясь учитывать требования.

2021-05-03 22:56 UTC, serhii-shkodenko requested changes
Поправь эти замечания и, скорее всего, будет аппрув.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/UI/ProductBuilder.cs
> +    public class ProductBuilder
Этот класс фактически - часть `SystemUI`, я не вижу причин для выделения одного метода в отдельный класс. Получается, построением интерфейса занимается две разных сущности. Лучше объединить в один класс.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/UI/SystemUI.cs
> +            _productBuilder = new ProductBuilder();
Объявление этой зависимости противоречит Dependency inversion principle. Однако после объединения классов, необходимость в ней отпадет (см. выше).

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/UI/SystemUI.cs
> +        private void CustomerMenu()
Методы должны содержать глагол. Возможно лучше его переназвать на `ShowCustomerMenu()`. Конвенция находится по адресу https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-type-members#names-of-methods

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Units/Base.cs
> +        public IList<Product> productBase;
Эти поля следует заменить свойствами. Не забудь про `PascalCase`.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public IList<Product> ProductBase { get => _innerBase.productBase; }
Тебе эти свойства на самом деле не нужны. У тебя есть класс `Base`, в котором уже есть публичные свойства. В этом классе можно лишь реализовать методы, которые в `IBase` добавляют/удаляют/изменяют данные.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public IList<Customer> CustomerBase { get => _innerBase.customerBase; }
См. выше.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public IList<Vendor> VendorBase { get => _innerBase.vendorBase; }
См. выше.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public BaseWorker(Base baseWithData)
Нарушение Dependency inversion principle. Добавь, пожалуйста, интерфейс `IBase` и в соответвующем параметре укажи его вместо `Base`.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        public void AddCustomer(Customer customer)
После реализации вышеуказанных рекомендаций, все последующие методы лучше разместить в соответствующих сервисах. Например, этот в `CustomerWorker` и так далее.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +    public class BaseWorker:IBaseWorker
После реализации нижеуказанных рекомендаций, необходимость в этом классе отпадет, поэтому удали его.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/BaseWorker.cs
> +        private void FillBaseWithDefaults()
Этот метод можно перенести в `IBase`.

2021-05-03 22:56 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CustomerWorker.cs
> +        public CustomerWorker(IBaseWorker unit)
Поскольку необходимости в `IBaseWorker `отпадет (после внесения изменений), сюда лучше передать `IBase`.

2021-05-04 21:13 UTC, serhii-shkodenko requested changes
Нашел что еще поправить. Поправь, пожлауйста, и будет аппрув.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/IBase.cs
> +        public IList<Product> ProductBase { get; set; }
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/ICustomerWorker.cs
> +        public void Create(Customer unit);
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/IOrderWorker.cs
> +        public IList<Product> OrderList { get; set; }
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/IProductWorker.cs
> +        public void Create(Product product);
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/ISystemUI.cs
> +        public void ShowMainMenu();
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/IUnit.cs
>          public string Name { get; set; }
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:13 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/IFaces/IVendorWorker.cs
> +        public void Create(Vendor unit);
Необходимости в модификаторе `public` в членах интерфейса нет. По умолчанию, они всегда `public`, поэтому его обычно опускают.

2021-05-04 21:21 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-05-04 21:21 UTC, merged