implemented logger
Oleksandr-Mokryi/Flash-n-Fresh pull request #5
Opened 2021-05-13 17:42 UTC by Oleksandr-Mokryi

2021-05-14 11:32 UTC, Oleksandr-Mokryi commented
Метод добавления новой записи не соответствует конвенции. Вечером исправлю.

2021-05-17 19:51 UTC, serhii-shkodenko requested changes
Все хорошо, но есть пару мелких моментов. Поправь их, пожалуйста, и будет аппрув.

2021-05-17 19:51 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Units/Order.cs
> +        public readonly Customer customer;
Поля не предназначены для того, чтобы быть видимыми извне класса. Они позволяют связывать данные и методы для работы с ними, то есть реализовывать инкапсуляцию. Здесь лучше использовать просто свойство. 

Если ты не хочешь, чтобы его значение можно было менять извне, сеттер можно сделать приватным. Тогда в конструкторе ты сможешь присвоить этому свойству значение, которое пришло в параметре.

2021-05-17 19:51 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/Logger.cs
> +    class Logger : ILogger
Модификатор доступа забыл.

2021-05-17 20:12 UTC, serhii-shkodenko approved these changes
Решение с `init` отличное. Выглядит хорошо, можно мержить.

2021-05-17 20:14 UTC, merged