implemented database saving on disk and loading with json serialization
Oleksandr-Mokryi/Flash-n-Fresh pull request #6
Opened 2021-05-19 18:01 UTC by Oleksandr-Mokryi

2021-06-03 19:58 UTC, serhii-shkodenko requested changes
У тебя файл хранилища уже грузит в конструкторе данные из файла. Будет логично сделать в ней метод `Save()` и вызывать его при внесении изменений в хранилище. Таким образом у тебя логика работы с данными будет скоцентирована в одном месте и избавит тебя от необходимости внедрения новой зависимости в классы с бизнес логикой. 

В методе `Save()` хранилища пользоваться зависимостью `IDataManager`.

2021-06-04 17:37 UTC, Oleksandr-Mokryi commented
Случайно сделал коммит в новую ветку. Замержил в эту.

2021-06-04 18:37 UTC, Oleksandr-Mokryi commented
Переделал всё под ObservableCollection и построил сохранение базы вокруг изменения коллекций.

2021-06-07 19:56 UTC, serhii-shkodenko approved these changes
Выглядит хорошо. Можно мержить.

2021-06-07 20:04 UTC, merged