implemented cache and used threads and delegates
Oleksandr-Mokryi/Flash-n-Fresh pull request #7
Opened 2021-05-29 18:12 UTC by Oleksandr-Mokryi

2021-05-29 22:05 UTC, serhii-shkodenko requested changes

2021-05-29 22:05 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +        private void AutoCacheUpdater<T>() where T : class
Имя метода не соответствует его сути, он обновляет весь кеш через равные промежутки времени. Лучше было бы его назвать `ClearCache()`, `InvalidateCache()` или как-то еще.

2021-05-29 22:05 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Workers/CacheManager.cs
> +            Thread.Sleep(300000);
Для выполнения таких задач обычно делают специальные спомагательный классы, Workers, Jobs. Они могут переодически запускаться и выполнять делегаты. Чтобы этого избежать тебе будет достаточно в кеше хранить время добавления последней записи, сравнивать его с текущим, если больше пяти минут то удалять существующий элемент.

2021-05-29 22:12 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Units/Cache.cs
> +        public IList<Product> CacheData { get; set; } = new List<Product>();
Я ориентируюсь по id товара. Я добавил свой Guid для каждого товара при его создании

2021-05-29 22:15 UTC, serhii-shkodenko commented on Flash.n.Fresh/Flash'n'Fresh/Units/Cache.cs
> +        public IList<Product> CacheData { get; set; } = new List<Product>();
У тебя может поменяться "версия" товара, могут измениться его свойства , доступные для изменения (измениться описание, количество доступного товара и так далее), а id товара не меняется.

2021-05-30 09:21 UTC, Oleksandr-Mokryi commented on Flash.n.Fresh/Flash'n'Fresh/Units/Cache.cs
> +        public IList<Product> CacheData { get; set; } = new List<Product>();
Я добавил для каждого товара временную метку с последним обновлением. Теперь при подтверждении заказа программа сверяет эту метку у товара в заказе и у товара в базе.

2021-06-07 16:35 UTC, merged